name: Dev Build/Release

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      custom_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: cmgriffing/github-tag-action@v6.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_suffix: "-dev"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Dev Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  release:
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: cmgriffing/action-electron-builder@v1.7.7
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          # release: ${{ endsWith(github.ref, '-dev') }}
          custom_tag: ${{ needs.build.outputs.custom_tag }}
